# Generated by Django 2.2.7 on 2019-11-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='')),
                ('link', models.URLField()),
                ('reference_app', models.CharField(blank=True, choices=[('мфо', 'мфо'), ('кредитные_карты', 'кредитные_карты')], max_length=50)),
            ],
        ),
    ]
