# Generated by Django 2.2.7 on 2019-11-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebarbanner',
            options={'verbose_name': 'Боковой баннер', 'verbose_name_plural': 'Боковые баннеры'},
        ),
    ]
