# Generated by Django 2.2.7 on 2019-11-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20191116_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarbanner',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
