# Generated by Django 2.2.7 on 2019-11-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_sidebarbanner_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarbanner',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sidebarbanner',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='sidebarbanner',
            name='reference_app',
            field=models.CharField(blank=True, choices=[('мфо', 'мфо'), ('кредитные_карты', 'кредитные_карты')], max_length=50, verbose_name='Приложение'),
        ),
    ]
