# Generated by Django 2.2.7 on 2019-11-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20191118_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarbanner',
            name='clicked',
            field=models.IntegerField(default=0, verbose_name='Переходов'),
        ),
    ]
