# Generated by Django 2.2.7 on 2019-11-18 10:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='URL')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('description', models.TextField(max_length=4000, verbose_name='Описание')),
                ('default_position', models.IntegerField(verbose_name='Дефолтная позиция')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('limit', models.IntegerField(verbose_name='Кредитный лимит')),
                ('maintenance', models.IntegerField(verbose_name='Обслуживание')),
                ('min_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ставка')),
                ('special_offer', models.BooleanField(verbose_name='Специальное предложение')),
                ('cashback', models.IntegerField(blank=True, verbose_name='Кэшбэк')),
                ('high_approval_rate', models.BooleanField(verbose_name='Высокий % одобрения')),
                ('issue_cost', models.CharField(max_length=20, verbose_name='Открытие')),
                ('courier', models.BooleanField(verbose_name='Доставка курьером')),
                ('documents', models.CharField(max_length=50, verbose_name='Документы')),
                ('history_rating', models.IntegerField(verbose_name='Кредитный рейтинг')),
                ('advantage1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Преимущество 1')),
                ('advantage2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Преимущество 2')),
                ('advantage3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Преимущество 3')),
                ('advantage4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Преимущество 4')),
                ('legal_info', models.TextField(max_length=2000, verbose_name='Юридическая информация')),
                ('promoted', models.BooleanField(verbose_name='Продвигаемое')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='rating')),
                ('count', models.IntegerField(default=0, verbose_name='Количество отзывов')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
                'ordering': ('default_position',),
            },
        ),
        migrations.CreateModel(
            name='UnverifiedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата написания')),
                ('text', models.TextField(max_length=4000, verbose_name='Комментарий')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unverified_comments', to='credit.Offer', verbose_name='Оффер')),
            ],
            options={
                'verbose_name': 'Непроверенный комментарий',
                'verbose_name_plural': 'Непроверенные комментарии',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата написания')),
                ('text', models.TextField(max_length=4000, verbose_name='Комментарий')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='credit.Offer', verbose_name='Оффер')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-date_created',),
            },
        ),
    ]
