# Generated by Django 2.2.7 on 2019-11-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='cashback',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кэшбэк'),
        ),
    ]
