# Generated by Django 2.2.7 on 2019-11-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_auto_20191118_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifiedcomment',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
    ]
