# Generated by Django 2.2.7 on 2019-11-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_auto_20191118_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unverifiedcomment',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='unverifiedcomment',
            name='user_agent',
        ),
    ]
