# Generated by Django 2.2.7 on 2019-11-12 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('default_position',)},
        ),
        migrations.AddField(
            model_name='offer',
            name='approval_time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='default_position',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='documents',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='high_approval_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='history_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='identification',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='legal_info',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_term',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='offer',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='special_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=4000)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfo.Offer')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
