# Generated by Django 2.2.7 on 2019-11-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0002_auto_20191112_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='approval_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='default_position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='documents',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='history_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='identification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='legal_info',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='offer',
            name='max_sum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='max_term',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
