# Generated by Django 2.2.7 on 2019-11-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0004_auto_20191112_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='high_approval_rate',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='promoted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='special_offer',
            field=models.BooleanField(),
        ),
    ]
