# Generated by Django 2.2.7 on 2019-11-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0005_auto_20191112_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=2),
            preserve_default=False,
        ),
    ]
