# Generated by Django 2.2.7 on 2019-11-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0006_offer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('default_position',), 'verbose_name': 'Оффер', 'verbose_name_plural': 'Офферы'},
        ),
        migrations.AddField(
            model_name='offer',
            name='link',
            field=models.SlugField(allow_unicode=True, default=2, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='approval_time',
            field=models.CharField(max_length=20, verbose_name='Одобрение'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='default_position',
            field=models.IntegerField(verbose_name='Дефолтная позиция'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='documents',
            field=models.CharField(max_length=50, verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='high_approval_rate',
            field=models.BooleanField(verbose_name='Высокий % одобрения'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='history_rating',
            field=models.IntegerField(verbose_name='Кредитный рейтинг'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='identification',
            field=models.CharField(max_length=50, verbose_name='Идентификация'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='legal_info',
            field=models.TextField(max_length=1000, verbose_name='Юридическая информация'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='max_sum',
            field=models.IntegerField(verbose_name='Максимальная сумма'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='max_term',
            field=models.IntegerField(verbose_name='Срок'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='min_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='promoted',
            field=models.BooleanField(verbose_name='Продвигаемое'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(allow_unicode=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='special_offer',
            field=models.BooleanField(verbose_name='Специальное предложение'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
