# Generated by Django 2.2.7 on 2019-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0007_auto_20191113_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
    ]
