# Generated by Django 2.2.7 on 2019-11-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0008_auto_20191113_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='advantage1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='advantage2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='advantage3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='advantage4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default='ss', max_length=4000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='legal_info',
            field=models.TextField(max_length=2000, verbose_name='Юридическая информация'),
        ),
    ]
