# Generated by Django 2.2.7 on 2019-11-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0009_auto_20191113_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='advantage1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Преимущество 1'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='advantage2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Преимущество 2'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='advantage3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Преимущество 3'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='advantage4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Преимущество 4'),
        ),
    ]
