# Generated by Django 2.2.7 on 2019-11-15 10:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0010_auto_20191113_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_created',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата написания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mfo.Offer', verbose_name='Оффер'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=4000, verbose_name='Комментарий'),
        ),
        migrations.CreateModel(
            name='UnverifiedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=4000)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unverified_comments', to='mfo.Offer')),
            ],
            options={
                'verbose_name': 'Непроверенный комментарий',
                'verbose_name_plural': 'Непроверенные комментарии',
                'ordering': ('-date_created',),
            },
        ),
    ]
