# Generated by Django 2.2.7 on 2019-11-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0012_offer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов'),
        ),
    ]
