# Generated by Django 2.2.7 on 2019-11-18 10:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0013_offer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifiedcomment',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='unverifiedcomment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата написания'),
        ),
        migrations.AlterField(
            model_name='unverifiedcomment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unverified_comments', to='mfo.Offer', verbose_name='Оффер'),
        ),
        migrations.AlterField(
            model_name='unverifiedcomment',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='unverifiedcomment',
            name='text',
            field=models.TextField(max_length=4000, verbose_name='Комментарий'),
        ),
    ]
