# Generated by Django 2.2.7 on 2019-11-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0014_auto_20191118_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='URL'),
        ),
    ]
