# Generated by Django 2.2.7 on 2019-11-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0015_auto_20191118_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifiedcomment',
            name='ip',
            field=models.GenericIPAddressField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unverifiedcomment',
            name='user_agent',
            field=models.CharField(default='dfgdfg', max_length=1000),
            preserve_default=False,
        ),
    ]
