# Generated by Django 2.2.7 on 2019-11-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0017_auto_20191118_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifiedcomment',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unverifiedcomment',
            name='user_agent',
            field=models.CharField(default='Unknown', max_length=1000),
            preserve_default=False,
        ),
    ]
