# Generated by Django 2.2.7 on 2019-11-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfo', '0020_auto_20191118_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='clicked',
            field=models.IntegerField(default=0, verbose_name='Переходов'),
        ),
    ]
